### ISSUE TITLE
Slack channels specified without # prefix in rollbar_notification config are detected as drift

### ISSUE THREAD

**Issue by alinazabara** [rollbar/terraform-provider-rollbar#285]
There is an issue when switching Rollbar <-> Slack integration auth from a personal Slack token to Rollbar bot token:

To have a rollbar_notification added, Slack channel needs to be specified without `#` prefix - the resource is created successfully in this case, if the channel is specified with `#` prefix, `terraform apply` fails with `Error: 1 Channel not found`.

The issue is that when adding channel names without `#`, the prefix `#` is still added under the hood, which is detected by Terraform as a drift. Therefore, every time we are trying to apply the very same Terraform code, it shows all (in our case 162) notifications as the ones 'to change'.

**Comment by nieblara** [comment]
Hi there @alinazabara, Is this still an issue for you? I know we have made some under the hood improvements to the way we qualify the prefix and want to make sure that this hasnt been resolved since you opened up this issue. 

If so, I'll work on getting someone to dig into this so that we dont try to update all 162+ notifications if we dont need to

**Comment by alinazabara** [comment]
Hi @nieblara, thanks for the reply.

The issue still persists, unfortunately. 

```
~ resource "rollbar_notification" "sys_rate_limit_nonprod" {

    - config {
        - channel              = "#rollbar-notifications-nonprod" -> null
        - show_message_buttons = true -> null
        - teams                = [] -> null
        - users                = [] -> null
    }
    + config {
        + channel              = "rollbar-notifications-nonprod"
        + show_message_buttons = true
        + teams                = []
        + users                = []
    }

    # (1 unchanged block hidden)
}
```

**Comment by nieblara** [comment]
Ok, Thank you. I think i know what's going on here! Let me get this on our roadmap!

**Comment by nieblara** [comment]
@alinazabara This should be fixed now, mind giving it another spin?

**Comment by alinazabara** [comment]
@nieblara Thanks, I've tried -> the issue persists. I have tried both:
- running as is gives 400+ `rollbar_notification` updates due to channel names being changed (`"#rollbar-notifications"` -> `"rollbar-notifications"`)
- adding `#` before the Slack channel name still fails with `Error: 1 Channel not found` on apply

**Comment by alinazabara** [comment]
We do not face this issue anymore. I'm closing the thread. Thank you!

**Comment by alinazabara** [comment]
Unfortunately, the issue occurs again. But this time the detected changes are not consistent. Sometimes there are 180 detected drifts -> the next `terraform plan` shows 274 changes -> then 211 -> etc (with no changes done to the terraform code). Could you please look into it?

**Comment by rollbar-bborsits** [comment]
@pawelsz-rb Can you check this out, please? I reproduced this issue on my computer with the latest provider last week.

**Comment by rollbar-bborsits** [comment]
@nieblara Pawel suspects that this is an API side issue. Can you look into it?

**Comment by vmahilevskyi** [comment]
@rollbar-bborsits Hi! 
Any news about the issue @alinazabara has raised?

**Comment by rollbar-bborsits** [comment]
This bug was fixed.
