### ISSUE TITLE
Inconsistent Error: 1 Channel not found

### ISSUE THREAD

**Issue by alinazabara** [rollbar/terraform-provider-rollbar#333]
We are experiencing random `Error: 1 Channel not found` errors during `terraform apply`. 

```
resource "rollbar_notification" "occurrence_rate_prod" {
  rule {
    filters {
      <...>
    }
    trigger = "occurrence_rate"
  }
  channel = "slack"
  config {
    show_message_buttons = true
    channel              = "rollbar-notifications-prod"
  }

  depends_on = [rollbar_integration.slack_integration]
}
```
After running terraform plan, we have `51 to change` terraform resources - all of those are `occurrence_rate` Slack notifications (due to [this](https://github.com/rollbar/terraform-provider-rollbar/issues/269) issue). When running `terraform apply`, we receive 10 `Error: 1 Channel not found` errors (sometimes there are only 2 errors, sometimes >10).

Changing the channel name to `#rollbar-notifications-prod` (with `#`) gives us an additional `Error: 1 The channel cannot be found` error for `rollbar_integration` resource (`Error: 1 Channel not found` also occur).

Here are examples of errors:

```
│ Error: 1 Channel not found
│
│   with module.account_service_notifications.rollbar_notification.occurrence_rate_prod,
│   on modules/rollbar-notifications/notifications_prod.tf line 48, in resource "rollbar_notification" "occurrence_rate_prod":
│   48: resource "rollbar_notification" "occurrence_rate_prod" {

```

```
│ Error: 1 The channel cannot be found
│
│   with module.event_streaming_service_notifications.rollbar_integration.slack_integration,
│   on modules/rollbar-notifications/slack_integration.tf line 1, in resource "rollbar_integration" "slack_integration":
│    1: resource "rollbar_integration" "slack_integration" {
```

**Comment by rollbar-bborsits** [comment]
@alinazabara Thanks for reporting this issue. We'll investigate what goes wrong and will get back to you when finding something out.

@pawelsz-rb Can you look into this one too? This seems to be connected with https://github.com/rollbar/terraform-provider-rollbar/issues/285

**Comment by rollbar-bborsits** [comment]
@nieblara Pawel suspects that this is an API-side issue. Can you look into it, please?

**Comment by BorisDr** [comment]
Any progress on that? Still have same issue

**Comment by rollbar-bborsits** [comment]
Hey @BorisDr, This issue should have been fixed by a previous release. Can you confirm the provider version you use?

**Comment by anmakove** [comment]
Still present on provider version `v1.12.0` if update many items in a row (more than 100). For example if I have 20 projects (1 project per service) and 11 rules for each project - I need to apply configuration 4-6 times because of `Error: 1 Channel not found` error.
Probably some kind of API throttling or requests limit
